# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summarization', models.CharField(max_length=100)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soltree.node')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soltree.problem')),
            ],
        ),
        migrations.CreateModel(
            name='sub_how_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_slice', models.ImageField(upload_to='')),
                ('order', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soltree.node')),
                ('orig_sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soltree.solution')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='prob_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soltree.problem'),
        ),
    ]
