# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0003_auto_20170801_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soltree.node'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='img',
            field=models.ImageField(upload_to='orig'),
        ),
        migrations.AlterField(
            model_name='sub_how_to',
            name='img_slice',
            field=models.ImageField(upload_to='slice'),
        ),
    ]
