# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0005_auto_20170829_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('node_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soltree.node')),
            ],
        ),
        migrations.CreateModel(
            name='node_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('node_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soltree.node')),
            ],
        ),
        migrations.RemoveField(
            model_name='sub_how_to',
            name='img_slice',
        ),
        migrations.RemoveField(
            model_name='sub_how_to',
            name='node_id',
        ),
        migrations.AddField(
            model_name='solution',
            name='tagged_img',
            field=models.ImageField(blank=True, null=True, upload_to='edit'),
        ),
        migrations.AddField(
            model_name='sub_how_to',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
