# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0006_auto_20170829_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='problem_pk',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='problem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='problem'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='tagged_img',
            field=models.ImageField(blank=True, null=True, upload_to='tag'),
        ),
    ]
