# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0007_auto_20170831_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soltree.problem'),
        ),
    ]
