# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0008_node_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='node_pk',
            new_name='node',
        ),
    ]
