# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0009_auto_20170905_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_inst',
            field=models.BooleanField(default=False),
        ),
    ]
