# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0010_annotation_is_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='img',
            field=models.ImageField(upload_to='orig/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
