# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0011_auto_20170906_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='img',
            field=models.ImageField(upload_to='orig/'),
        ),
    ]
