# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0012_auto_20170906_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='answer')),
                ('text', models.CharField(max_length=1000)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soltree.problem')),
            ],
        ),
    ]
