# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0014_auto_20170907_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
