# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0015_auto_20170907_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
