# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0016_solution_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_text',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
