# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0017_node_text_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='node',
            new_name='cur_node',
        ),
    ]
