# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0018_auto_20170915_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='cur_node',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='node_text',
            old_name='node_pk',
            new_name='node',
        ),
    ]
