# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltree', '0019_auto_20170915_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='right_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='tot_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='tot_count',
            field=models.IntegerField(default=0),
        ),
    ]
